---
- name: simple test windows connection
  hosts: win10pc.tingnkai.com

  tasks:
    - name: Compress the directories contents
      community.windows.win_zip:
        src: D:\test\*
        dest: D\test.zip
