---
- name: test
  hosts: localhost
  tasks: 
    - name: test
      debug:
        msg: "{{ ansible_date_time.iso8601_micro }}"

    - name: test
      debug:
        var: ansible_facts['hostname']
      when: inventory_hostname == 'localhost'
