---
- name: update Win DNS records
  hosts: all
  vars:
    target_name: "kai"
    target_type: "A"
    target_ip: "1.2.3.4"
    target_zone: "tingnkai.com"
  gather_facts: false

  tasks:
    - name: Ansible Ping
      ansible.windows.win_ping:

    - name: Update DNS recrod
      ansible.windows.win_dns_record:
        computer_name: "dc01.tingnkai.com"
        name: "{{ target_name }}"
        type:  "{{ target_type }}"
        value:  "{{ target_ip }}"
        zone: "{{ target_zone }}"
      register: record_update
      tags: not remove

    - name: Remove static record
      ansible.windows.win_dns_record:
        name: "{{ target_name }}"
        type: "{{ target_type }}"
        state: absent
        zone: "{{ target_zone }}"
      register: record_update
      tags: [ never, remove ]
      
    - debug:
        var: record_update
