---
- name: simple test windows connection
  hosts: "win01.tingnkai.com"
  vars:
    Path: "C:\\Windows\\System32\\drivers\\etc"
    FileName: "hosts"
    Target: "dc01.tingnkai.com"
  tasks:
    - name: test win
      win_ping:

    - name: Run PowerShell script with parameters
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param (
              [String]
              $Path,

              [String]
              $target
          )
          $session = New-PSSession -ComputerName $target
          Copy-Item -FromSession $session -Path $Path -Destination "C:\Temp"
          Remove-PSSession -Session $session
        parameters:
          target: "{{ Target }}"
          Path: "{{ Path }}\\{{ FileName }}"

    - name: copy file
      fetch: 
        src="{{ Path }}\\{{ FileName }}"
        dest=~/{{ FileName }}
        flat=yes

    - name: test output
      command: cat ~/{{ FileName }}
      delegate_to: localhost
      
    - name: Ensure file is absent
      ansible.windows.win_file:
        path: "C:\Temp\{{ FileName }}"
        state: absent
