---
- name: RouterOS test with network_cli connection
  hosts: routers
  gather_facts: false
  tasks:

  - name: Run command on remote devices
    community.routeros.command:
      commands: /system routerboard print
