---
- name: Update DNS records
  hosts: linux
  gather_facts: true
  tasks:
    - name: Update two IPv4 DNS server addresses
      community.general.nmcli:
        conn_name: ens192
        type: ethernet
        dns4:
          - 192.168.155.11
          - 192.168.155.10
        dns4_options: 
          - timeout:1
          - attempts:1
        state: up
        conn_reload: true
