---
- name: Install key by Ansible
  hosts: all

  tasks:
  - name: Ensure Key in ~/.ssh/id_rsa.pub
    authorized_key:
      user: root
      state: present
      key: '{{ item }}'
    with_file:
      - ~/.ssh/id_rsa.pub
