---
- name: Add execution_environment
  hosts: aap2.lab.tingnkai.com
  tasks: 
    - name: Add EE to the controller instance
      execution_environment:
        name: "OCP4-ee"
        image: "hub2.lab.tingnkai.com/ee-ocp4:latest"
