---
- name: Add execution_environment
  hosts: aap2.lab.tingnkai.com
  collections:
    - ansible.controller
  tasks: 
    - name: Add EE to the controller instance
      execution_environment:
        name: "tingnkai-ee"
        image: "hub2.lab.tingnkai.com/tingnkai-ee:v2.0"
