---
---
- name: Configure AAP
  hosts: localhost
  gather_facts: false
  tasks: 
    - name: Add EE to the controller instance
      ansible.controller.execution_environment:
        name: "OCP4-ee"
        image: "hub2.lab.tingnkai.com/ee-ocp4:latest"
